version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: .
    deploy:
      replicas: 4
      resources:
        limits:
          cpus: "0.25"
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
    networks:
      - webnet
networks:
  webnet: